#!/usr/bin/env python
'''
Copyright 2017, Fujitsu Network Communications, Inc.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
'''
import sys
if sys.version_info < (2, 7):
    print "Warrior doesn't support Python version lower than 2.7, now exiting"
    sys.exit(0)

try:
    from WarriorCore import warrior_cli_driver
    from Framework.Utils.print_Utils import print_info
except:
    raise

"""
This is the Warrior executable
"""

def main(**kwargs):
    """
        main method
        filepath: required at least one
        mockrun:
        auto_defects:
        version:
        iron_claw:
        jiraproj:
        overwrite:
        jiraid:
        dbsystem:
        livehtmllocn:
    """
    if not kwargs:
        # Launch from terminal/cli exeuction
        filepath, cli_args, overwrite = warrior_cli_driver.main(sys.argv[1:])
    else:
        # Launch from python function call
        filepath, cli_args, overwrite = warrior_cli_driver.main(**kwargs)

    status = warrior_cli_driver.execution(filepath, cli_args, overwrite)
    status = {"true": True, "pass": True}.get(str(status).lower())
    # add code to send div finished using katana interface class

    if status is True:
        print_info("DONE 0")
        sys.exit(0)
    else:
        print_info("DONE 1")
        sys.exit(1)

if __name__ == '__main__':
    main()
